# Data class/types human-friendly name
PHP_APE_Type_Boolean = 'boolean' 
PHP_APE_Type_Integer = 'integer' 
PHP_APE_Type_Byte = 'tiny integer' 
PHP_APE_Type_UByte = 'unsigned tiny integer' 
PHP_APE_Type_Int2 = 'small integer' 
PHP_APE_Type_UInt2 = 'unsigned small integer' 
PHP_APE_Type_Int4 = 'integer' 
PHP_APE_Type_Int8 = 'big integer' 
PHP_APE_Type_Float = 'floating-point number' 
PHP_APE_Type_Float4 = 'small floating-point number' 
PHP_APE_Type_Float8 = 'floating-point number' 
PHP_APE_Type_Decimal = 'decimal number' 
PHP_APE_Type_Money = 'money amount' 
PHP_APE_Type_Date = 'date' 
PHP_APE_Type_Time = 'time' 
PHP_APE_Type_Timestamp = 'date+time' 
PHP_APE_Type_Angle = 'angle' 
PHP_APE_Type_String = 'single-line text' 
PHP_APE_Type_Char = 'single character' 
PHP_APE_Type_Text = 'multi-line text' 
PHP_APE_Type_Password = 'password' 
PHP_APE_Type_Email = 'e-mail address' 
PHP_APE_Type_URL = 'hyperlink' 
PHP_APE_Type_Path = 'file path' 
PHP_APE_Type_Dir = 'directory path' 
PHP_APE_Type_File = 'file name' 
PHP_APE_Type_FileFromUpload = 'uploaded file path' 
PHP_APE_Type_Index = 'index/identifier' 

# Character-based types samples
PHP_APE_Type_Int8.Sample = '123' 
PHP_APE_Type_String.Sample = 'Hello World !' 
PHP_APE_Type_Char.Sample = 'A' 
PHP_APE_Type_Text.Sample = 'Hello World !' 
PHP_APE_Type_Password.Sample = '******' 
PHP_APE_Type_Email.Sample = 'user.name@domain.tld' 
PHP_APE_Type_URL.Sample = 'http://server.domain.tld/path' 
PHP_APE_Type_Path.Sample = '/path/to/file.ext' 
PHP_APE_Type_Dir.Sample = '/path/to/file.ext' 
PHP_APE_Type_File.Sample = '/path/to/file.ext' 
PHP_APE_Type_FileFromUpload.Sample = '(My Computer)/path/to/file.ext' 
PHP_APE_Type_Index.Sample = 'ID#123' 

# Other values
PHP_APE_Type_Any.Value = 'value' 
PHP_APE_Type_String.Length = 'length' 
