# (French version)
# Data class/types human-friendly name
PHP_APE_Type_Boolean = 'bool' 
PHP_APE_Type_Integer = 'entier' 
PHP_APE_Type_Byte = 'très petit entier' 
PHP_APE_Type_UByte = 'très petit entier non-signé' 
PHP_APE_Type_Int2 = 'petit entier' 
PHP_APE_Type_UInt2 = 'petit entier non-signé' 
PHP_APE_Type_Int4 = 'entier' 
PHP_APE_Type_Int8 = 'grand entier' 
PHP_APE_Type_Float = 'nombre réel' 
PHP_APE_Type_Float4 = 'petit nombre réel' 
PHP_APE_Type_Float8 = 'nombre réel' 
PHP_APE_Type_Decimal = 'nombre décimal' 
PHP_APE_Type_Money = 'montant' 
PHP_APE_Type_Date = 'date' 
PHP_APE_Type_Time = 'heure' 
PHP_APE_Type_Timestamp = 'date+heure' 
PHP_APE_Type_Angle = 'angle' 
PHP_APE_Type_String = 'texte à ligne unique' 
PHP_APE_Type_Char = 'caractère unique' 
PHP_APE_Type_Text = 'texte à lignes multiples' 
PHP_APE_Type_Password = 'mot de passe' 
PHP_APE_Type_Email = 'adresse e-mail' 
PHP_APE_Type_URL = 'lien Internet' 
PHP_APE_Type_Path = 'chemin de fichier' 
PHP_APE_Type_Dir = 'chemin de répertoire' 
PHP_APE_Type_File = 'nom de fichier' 
PHP_APE_Type_FileFromUpload = 'nom de fichier téléchargé' 
PHP_APE_Type_FileAsDownload = 'nom de fichier téléchargeable' 
PHP_APE_Type_FileAsImage = 'nom de fichier image' 
PHP_APE_Type_FileAsSound = 'nom de fichier son' 
PHP_APE_Type_FileAsMovie = 'nom de fichier vidéo' 
PHP_APE_Type_Index = 'index/identifiant' 

# Character-based types samples
PHP_APE_Type_Int8.Sample = '123' 
PHP_APE_Type_String.Sample = 'Hello World !' 
PHP_APE_Type_Char.Sample = 'A' 
PHP_APE_Type_Text.Sample = 'Hello World !' 
PHP_APE_Type_Password.Sample = '******' 
PHP_APE_Type_Email.Sample = 'nom.utilisateur@domaine.tld' 
PHP_APE_Type_URL.Sample = 'http://serveur.domaine.tld/chemin' 
PHP_APE_Type_Path.Sample = '/chemin/vers/fichier.ext' 
PHP_APE_Type_Dir.Sample = '/chemin/vers/fichier.ext' 
PHP_APE_Type_File.Sample = '/chemin/vers/fichier.ext' 
PHP_APE_Type_FileFromUpload = '(Mon Poste de Travail)/chemin/vers/fichier.ext' 
PHP_APE_Type_Index = 'ID#123' 

# Other values
PHP_APE_Type_Any.Value = 'valeur' 
PHP_APE_Type_String.Length = 'longueur' 
