# (French version)
# Data class/types human-friendly name
PHP_APE_Type_Boolean = 'bool' 
PHP_APE_Type_Integer = 'entier' 
PHP_APE_Type_Byte = 'tr&egrave;s petit entier' 
PHP_APE_Type_UByte = 'tr&egrave;s petit entier non-sign&eacute;' 
PHP_APE_Type_Int2 = 'petit entier' 
PHP_APE_Type_UInt2 = 'petit entier non-sign&eacute;' 
PHP_APE_Type_Int4 = 'entier' 
PHP_APE_Type_Int8 = 'grand entier' 
PHP_APE_Type_Float = 'nombre r&eacute;el' 
PHP_APE_Type_Float4 = 'petit nombre r&eacute;el' 
PHP_APE_Type_Float8 = 'nombre r&eacute;el' 
PHP_APE_Type_Decimal = 'nombre d&eacute;cimal' 
PHP_APE_Type_Money = 'montant' 
PHP_APE_Type_Date = 'date' 
PHP_APE_Type_Time = 'heure' 
PHP_APE_Type_Timestamp = 'date+heure' 
PHP_APE_Type_Angle = 'angle' 
PHP_APE_Type_String = 'texte &agrave; ligne unique' 
PHP_APE_Type_Char = 'caract&egrave;re unique' 
PHP_APE_Type_Text = 'texte &agrave; lignes multiples' 
PHP_APE_Type_Password = 'mot de passe' 
PHP_APE_Type_Email = 'adresse e-mail' 
PHP_APE_Type_URL = 'lien Internet' 
PHP_APE_Type_Path = 'chemin de fichier' 
PHP_APE_Type_Dir = 'chemin de r&eacute;pertoire' 
PHP_APE_Type_File = 'nom de fichier' 
PHP_APE_Type_FileFromUpload = 'nom de fichier t&eacute;l&eacute;charg&eacute;' 
PHP_APE_Type_FileAsDownload = 'nom de fichier t&eacute;l&eacute;chargeable' 
PHP_APE_Type_FileAsImage = 'nom de fichier image' 
PHP_APE_Type_FileAsSound = 'nom de fichier son' 
PHP_APE_Type_FileAsMovie = 'nom de fichier vid&eacute;o' 
PHP_APE_Type_Index = 'index/identifiant' 

# Character-based types samples
PHP_APE_Type_Int8.Sample = '123' 
PHP_APE_Type_String.Sample = 'Hello World !' 
PHP_APE_Type_Char.Sample = 'A' 
PHP_APE_Type_Text.Sample = 'Hello World !' 
PHP_APE_Type_Password.Sample = '******' 
PHP_APE_Type_Email.Sample = 'nom.utilisateur@domaine.tld' 
PHP_APE_Type_URL.Sample = 'http://serveur.domaine.tld/chemin' 
PHP_APE_Type_Path.Sample = '/chemin/vers/fichier.ext' 
PHP_APE_Type_Dir.Sample = '/chemin/vers/fichier.ext' 
PHP_APE_Type_File.Sample = '/chemin/vers/fichier.ext' 
PHP_APE_Type_FileFromUpload.Sample = '(Mon Poste de Travail)/chemin/vers/fichier.ext' 
PHP_APE_Type_Index.Sample = 'ID#123' 

# Other values
PHP_APE_Type_Any.Value = 'valeur' 
PHP_APE_Type_String.Length = 'longueur' 
