#!/bin/bash
set -e

case "$1" in

  configure)
    # Set appropriate permissions
    chown -R root:www-data /etc/php-ape /var/lib/php-ape /var/cache/php-ape /var/log/php-ape
    chmod -R g+r,g-w,o= /etc/php-ape
    chmod g+rws,o= /var/lib/php-ape /var/cache/php-ape /var/log/php-ape

    # Enable apache configuration
    ln -s /etc/php-ape/apache.conf /etc/apache2/conf.d/php-ape.conf
    echo 'WARNING: Please reload apache configuration to enable php-ape!'
    ;;

esac

exit 0

